name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install dependencies
        run: |
          cd tests
          go get github.com/gruntwork-io/terratest/modules/...
          go get github.com/stretchr/testify

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: terraform

      - name: Run Terratest
        run: go test -v -timeout 30m
        working-directory: tests

      - name: Lint with TFLint
        uses: terraform-linters/setup-tflint@v1
      - run: tflint --config=terraform/.tflint.hcl
        working-directory: terraform
